### ISSUE TITLE
Real intended dedicated "Viewer" component

### ISSUE THREAD

**Issue by CreativeHouseDotOrg** [BenjaminBrandmeier/angular2-image-gallery#125]
Dear Benjamin

It would be great to have a dedicated Viewer Component that can be intentionally placed somewhere in the html template.

As for now it's possible to place the "Viewer" Component of your library somewhere in the angular application but the problem is that the second viewer still gets shown in the background. It was possible to hide the embedded viewer (the one in the background) using some css tweaks but it would be nice to have some out of the box functionalities for this kind of usecase.

For example it would be really helpful if there would be an option like a boolean flag on the "Gallery" Component to hide the default embed viewer and to only use the one viewer that we set manually (mostly at the most upper template of the application to help with z-index problems or scrolling issues since "position:fixed" doesn't work when using the viewer in nested components since the viewer is being created there, not respecting the components above it).

Neitherless thank you for your great work so far and looking forward to your answer.

Kind regards

Mike from Creative-House.org

**Comment by BenjaminBrandmeier** [comment]
Hi Mike,

thanks for the suggestion. This sounds interesting, no sure though how big the interest in such a feature is throughout the angular2-image-gallery users. 

So upvoting Mikes suggestion helps me in prioritizing!


> Dear Benjamin
> 
> It would be great to have a dedicated Viewer Component that can be intentionally placed somewhere in the html template.
> 
> As for now it's possible to place the "Viewer" Component of your library somewhere in the angular application but the problem... 

Do you have an example of how you are currently using it? Are you using the viewerChange event to separate the viewer from the gallery component?

**Comment by CreativeHouseDotOrg** [comment]
Sure you can give a look here:

[https://www.fraumattahof.ch/bio-fleisch-aus-graubuenden](https://www.fraumattahof.ch/bio-fleisch-aus-graubuenden)


As you can see the viewer gets opened twice when clicking on a picture. My temporary solution is to move the viewer of the gallery component to the background allthough it's still not completely invisible but managed to get it to the background where it isn't that much noticeable. But it's still there.

My Code looks something like this:

In the `app.component.html` file

    <viewer></viewer>
    <router-outlet></router-outlet>

In the `app.component.scss` file

    viewer 
    {
      z-index:99999; // since our application uses some elements above 1031
      position: fixed;
    }

In the global `style.scss` file

    .outerContainer {
        z-index: -2 !important;
    }
    
Oh and before I forgett: Happy Easter! 🐇🥚

**Comment by BenjaminBrandmeier** [comment]
Please check the latest 15.1.0 version. I have added an option [includeViewer] which, in your use case, you want to set to false. This removes all of the embedded viewers.

Please let me know if this quick-fix helps. It's hard to take a look at your website without getting hungry. ;-)

**Comment by CreativeHouseDotOrg** [comment]
Thanks a lot, seems working like intended!

Glad I'm not the only one suffering from the hunger games 😉

The meat of Fraumattahof is actually pretty amazing, very natural and of high quality. If there is a way I can offer you a pair of "Swiss Salsiz" as a thank you please let me know by writing a mail to info@creative-house.org 🙂

Thanks again!
