### ISSUE TITLE
Multiple galleries not working

### ISSUE THREAD

**Issue by maxGross** [BenjaminBrandmeier/angular2-image-gallery#25]
### Error when using several gallery names  @f14424b46d2f33f6366db0cc790aa2e471f8e975
e.g. [galleryName]="myGallery" 
Console output tells following error: 
> 404 Not Found for URL: _http://localhost:4200/assets/img/gallery/undefined/data.json_

- Images are provided at the local file structure
- Using the gallery with default root path for all images works fine.

**Comment by maxGross** [comment]
my fault ...
works great!

**Comment by stefan-frank** [comment]
What was your fault? It seems someone else and me are making the same fault as well...

**Comment by maxGross** [comment]
I used the @Input() variable like this: `[galleryName]="galleryName"`
My assumption was that this will refer to the the gallery folder named _galleryName_. But of course this won't work cause angular will look for a variable named _galleryName_! 
So i declared a variable `galleryName = "myGalleryFolder"` and it works.

**Comment by stefan-frank** [comment]
Thanks for your explanation. It works for me as well. The documentation might be enhanced to prevent further misunderstandings.

**Comment by rustygreen** [comment]
Just to note, you could do it without declaring a variable (like you were trying to originally), but you'd have to put quotes around the gallery name: `[galleryName]="'galleryName'"`

**Comment by BenjaminBrandmeier** [comment]
I changed the README to include the single quotes, since this looks more intuitive.
