### ISSUE TITLE
 I am suggesting a bug fix on "Windows 10"

### ISSUE THREAD

**Issue by heidrion** [BenjaminBrandmeier/angular2-image-gallery#28]
Hello.
I am a Korean developer.
We will let you know in advance that it was written in Google Translator. ^^ ;;;;
(Please ... hope to be able to communicate)

First of all, thank you very much for sharing the excellent "Component".
It is very small, but I hope to share the problem in use and hope to be helpful.

The "desktop.ini" file generated automatically by the OS causes an error when "gm convert".

I corrected it by correcting it as follows.
[Before]
_If (file! = '.gitignore') ..._

[After]
_**If (file! = '.gitignore' && file.indexOf ('. Ini') == -1) {**_

In the long term, it is recommended to support valid image extensions as arguments when running "convert.js".

Thank you. Healthy ~

**Comment by BenjaminBrandmeier** [comment]
Hello heidrion.

I'm glad you like my gallery! I will provide a fix for this issue with valid image extensions as soon as I have time for it.

**Comment by BenjaminBrandmeier** [comment]
I'm now checking for supported file type extensions. I published a new version 0.6.1 which includes the changes. Please try again with the new version. If there are any remaining issues feel free to comment here again. :)
