### ISSUE TITLE
Can't execute node script

### ISSUE THREAD

**Issue by joandvgv** [BenjaminBrandmeier/angular2-image-gallery#33]
I can't execute the node script provided.
I did npm install -g gm 
It is also in my local project node_modules folder but it says the following:

> Converting images...

> C:\Users\myuser\Documents\totalautospzo\folder\IMG_20170114_121142.jpg

> Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-verbose" "C:\Users\myuser\Documents\totalautospzo\folder\IMG_20170114_121142.jpg" this most likely means the gm/convert binaries can't be found

What can I do in order to make it work?

**Comment by joandvgv** [comment]
Well, just ignore this please. I'm so sorry. Completely forgot to install the binaries, don't know what i was thinking.

**Comment by BenjaminBrandmeier** [comment]
Please ignore the commits above. They should belong to #22. ;)
