### ISSUE TITLE
Migrate to Angular 4

### ISSUE THREAD

**Issue by BenjaminBrandmeier** [BenjaminBrandmeier/angular2-image-gallery#34]
Migrate to Angular 4 and ensure that everything (especially Animations) are still working on all major browsers + mobile.

When using the project currently in an Angular 4 environment with Angular-CLI 1.0.0 IE 11 is broken.

**Comment by rustygreen** [comment]
Thanks @BenjaminBrandmeier, this is a great component you put together! Do you have any idea on when you are planning to add CLI 1.0.0 support?

**Comment by BenjaminBrandmeier** [comment]
@rustygreen Thanks. As soon as I have some time. Will start with this shortly: https://github.com/BenjaminBrandmeier/angular2-image-gallery/issues/39

**Comment by BenjaminBrandmeier** [comment]
Migration to Angular 4 and angular-cli 1.0.0 completed.
