### ISSUE TITLE
Multiple galleries - lightbox viewer shows only the "last" gallery

### ISSUE THREAD

**Issue by tomteman** [BenjaminBrandmeier/angular2-image-gallery#40]
If you have multiple galleries, clicking an image to open the viewer doesn't update the "images" in the service, and therefore all the listeners to the `ImageService` observable (in this case the viewer) show the last "images" passed to the service, which is the last gallery during initialization.

The fix is that each gallery component calls `ImageService`'s `next()` (via the `updateImages(gallery)` method) before opening the viewer, thus updating all listeners (including the viewer) that this is the relevant image gallery.

I have created a pull request with the fix:
https://github.com/BenjaminBrandmeier/angular2-image-gallery/pull/37

**Comment by BenjaminBrandmeier** [comment]
Sounds good to me. Will have a look at this within the next days to merge and publish a new version. :)

**Comment by BenjaminBrandmeier** [comment]
Merged #37 and released as 0.7.2.
