### ISSUE TITLE
Lazy Load this module causes 'BrowserModule has already been loaded' error

### ISSUE THREAD

**Issue by ssglopes** [BenjaminBrandmeier/angular2-image-gallery#46]
Lazy load this module to trigger the error. The error happens because BrowserAnimationsModule (as BrowserModule) can be included only ones in a project.
It's caused by this line: animations_1.BrowserAnimationsModule inside file angular2imagegallery.module.js
as when commented out it works and relates to:
https://github.com/angular/angular-cli/issues/5684 => post: Perezmarc commented on Mar 29.

**Comment by karthik04** [comment]
Same problem here. Lazy loading BrowserAnimationsModule or NoopAnimationsModule throws following error,
`ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

**Comment by johndi9** [comment]
Are there any news on this side? I get the same issue as @ssglopes. What I'm doing for the moment is commenting too `BrowserAnimationsModule` after installing the dependency.

**Comment by BenjaminBrandmeier** [comment]
Please try it again now with the newest published version (6.0.0).

**Comment by karimzg** [comment]
Still not working with 6.0.2. Any idea of when it could be fixed?
