### ISSUE TITLE
Script problem

### ISSUE THREAD

**Issue by GeekyWill** [BenjaminBrandmeier/angular2-image-gallery#48]
I'm sure it's not the script I'm just clueless as how to run it

node node_modules/angular2-image-gallery/convert.js <path/to/your/images>

I'm stuck on this part "<path/to/your/images>"

I'm pretty sure you run this in the terminal right?

**Comment by JennHaggerty** [comment]
Correct, you run this command in the terminal and replace the last part with your path.
`node node_modules/angular2-image-gallery/convert.js /image/jpegs/01.jpg`
