### ISSUE TITLE
Adding headers to metadataUri url request

### ISSUE THREAD

**Issue by elmartino** [BenjaminBrandmeier/angular2-image-gallery#49]
Hi!

Is it possible to add headers to the metadataUri url request? I need this for authentication purposes tot the external Uri.

Another option would be to support the use of a custom local array. Then i could request the data from my external datasource using my own http interceptor for the headers.

Thanks in advance!
Regards,
Martin

**Comment by BenjaminBrandmeier** [comment]
This is an opinionated library with very limited support for serving data through remote locations. I'd recommend you fork this project and add your custom headers, the implementation should be basic.
