### ISSUE TITLE
Problem if i use multiple galleries

### ISSUE THREAD

**Issue by jenny59** [BenjaminBrandmeier/angular2-image-gallery#58]
I use 3 photo galleries which can be selected via TabControl. The first (default) always works, 

![2017-10-01 12_39_15-jlabimagegallery-ok](https://user-images.githubusercontent.com/13096134/31053911-52dfc814-a6a7-11e7-932d-91716a04c45c.png)
                          (Gallery 1 is ok)

<br>
the other two do not, the thumbnail is not displayed correctly. 

![2017-10-01 12_38_12-jlabimagegallery-nok](https://user-images.githubusercontent.com/13096134/31053921-7f9670a6-a6a7-11e7-9d05-d4fc420c21fa.png)
                          (Gallery 2 and 3 is not ok)

<br>
It works only if I reduce the Broser window or enlarge it.

Here is my HTML code:

<div class="gallery-main-area">

<gallery class="gallery-item" [flexBorderSize]="3"  [flexImageSize]="7" 
        [galleryName]="'Stoss-12.-13.08.2017'"  (viewerChange)="notificationFunction($event)">
</gallery>

<gallery class="gallery-item" [flexBorderSize]="3" [flexImageSize]="7"
        [galleryName]="'AWeisenstein1'" (viewerChange)="notificationFunction($event)">
</gallery>

<gallery class="gallery-item" [flexBorderSize]="3" [flexImageSize]="7"
       [galleryName]="'BWeisenstein2'" (viewerChange)="notificationFunction($event)">
</gallery>

</div>

Which I make with the select visible.

this.galleryItems = $ ('. gallery-item');
this.galleryItems.hide ();
$ (This.galleryItems [tab.index]) show ().

What could be the problem?
Thanks for your help

**Comment by BenjaminBrandmeier** [comment]
Hey jenny,

if you still around, kindly re-check with the latest version. If the issue still persists I'm glad to take a closer look at this.

**Comment by BenjaminBrandmeier** [comment]
Within the latest release of 15.2.0 I have provided an option to disable lazy loading entirely. This might fix the described problems you have as well.

Since this issue is open for quiet a while without any activity I will close it for now. If the problem persists, feel free to open another issue.
