### ISSUE TITLE
ERROR TypeError: _this.images.forEach is not a function

### ISSUE THREAD

**Issue by JennHaggerty** [BenjaminBrandmeier/angular2-image-gallery#59]
I'm using an external source, 500px, for my images and am able to read the data by following the link however when I use the code `<gallery [metadataUri]="'https://api.500px.com/v1/photos?...'"></gallery>` I receive the error: ERROR TypeError: _this.images.forEach is not a function

**Comment by BenjaminBrandmeier** [comment]
Did you provide the required JSON file at 500px?
