### ISSUE TITLE
Nav bar on top of the image view

### ISSUE THREAD

**Issue by karan-kapoor90** [BenjaminBrandmeier/angular2-image-gallery#60]
On both, mobile and desktop, the image view coming behind the nav bar for some reason. Because of this the gallery doesn't work properly... is this a known issue?

Further, on mobile, the image view isn't responsive in this given scenario, so you don't see the 'x' to close the image view and you see the zoomed in section of the image - whatever fits your screen, not the whole image.

I'm not sure where to start debugging this :(

**Comment by unbekannt3DE** [comment]
Have the same issue with mdbootstrap, tried to add a padding to the viewer container but doesn't work.

**Comment by MiguelZablah** [comment]
Have the same issue on bootstrap 4 navbar fixed and also with some bootstrap 4 buttons

**Comment by mathsusan** [comment]
I added 
.outerContainer[_ngcontent-c2]{
    z-index: 1031;
}

to my css and it seems to work, problem seems to be the z-index of the fixed navbar

**Comment by BenjaminBrandmeier** [comment]
@mathsusan Thanks for the support. I added the zindex to the outerContainer CSS. It will be part of the next published version of the gallery (6.0.2+).
