### ISSUE TITLE
rollup make this issue when I rollup my app

### ISSUE THREAD

**Issue by bernardschyns** [BenjaminBrandmeier/angular2-image-gallery#61]
When I run my angular-cli app with jit, I get no problem..
When I try to roll-up following the "tour of heroes" documentation of angular....I catch this message error about "angular2-image-gallery"...

src/main-aot.js → aot/dist/build.js...
'angular2-image-gallery' is imported by src/app/app.module.js, but could not be resolved – treating it as an external dependency

**Comment by BenjaminBrandmeier** [comment]
Please try again with the newest published version. It was published with the angular package format.
