### ISSUE TITLE
convert.js error

### ISSUE THREAD

**Issue by Danubius1st** [BenjaminBrandmeier/angular2-image-gallery#63]
node node_modules/angular2-image-gallery/convert.js <path/to/your/images> --gName=yourGalleryName

TypeError: Cannot read property 'name' of undefined
    var filePath = assetsAbsoluteBasePath + resolution.name + '/' + imgMetadata. name;
                                                                                                                                 ^
node -v
v8.7.0

**Comment by Roundaround** [comment]
Getting the same error on Node v7.2.1

**Comment by Roundaround** [comment]
Did some digging, looks like this is an error at convert.js:112. Collecting the file extension is currently using indexOf to find the start of the extension, when it should instead be using lastIndexOf. Will make a pull request.

@Danubius1st as a workaround in the meantime you can replace line 112 of convert.js with this:
`        var extension = file.substring(file.lastIndexOf(".")+1, file.length);`

**Comment by BenjaminBrandmeier** [comment]
will be included in the next library release. if needed now, take the file from this source repo.
