### ISSUE TITLE
Unwanted image rotation

### ISSUE THREAD

**Issue by shanieMoonlight** [BenjaminBrandmeier/angular2-image-gallery#64]
Hi,

I'm using your angular2-image-gallery and find it very useful.
I'm having one problem though. All my portrait oriented images are being shown in landscape format.
I've checked the underlying files and they are in portrait orientation.

Is there a setting I'm leaving out?

Thanks
Shane

**Comment by v-bodnar** [comment]
I'm also facing the same problem!
I think problem is that photos are actually saved in landscape format, but your camera saves [exif data ](http://jpegclub.org/exif_orientation.html) and because of that most viewers automatically rotate it. Browser does not rotate them though. So extra check for exif tag orientation is needed in the code of the gallery.

**Comment by v-bodnar** [comment]
Added some temporal resolution that works for me. 'orientation' property has to be added to json.
It can be found in the forked https://github.com/v-bodnar/angular2-image-gallery

**Comment by IIvanov8888** [comment]
@v-bodnar 
I got the latest master branch of your **angular2-image-gallery** and got the following error 
```javascript
core.js:1440 ERROR TypeError: Cannot read property 'cameraModel' of undefined
    at GalleryComponent.parseExifData (gallery.component.ts:143)
    at Object.eval [as updateRenderer] (GalleryComponent.ngfactory.js:21)
    at Object.updateRenderer (core.js:14279)
    at checkAndUpdateView (core.js:13800)
    at callViewAction (core.js:14146)
    at execEmbeddedViewsAction (core.js:14104)
    at checkAndUpdateView (core.js:13796)
    at callViewAction (core.js:14146)
    at execEmbeddedViewsAction (core.js:14104)
    at checkAndUpdateView (core.js:13796)
```

**Comment by v-bodnar** [comment]
@IIvanov8888 
Thanks fixed it in the commit 7a06e340c498981e97eaebf1c6f2c73185fc0a26
But if you just need orientation check out 571099c49334180a69d723fa1374cce12d87bbd5 later I have added few libraries and some code for my private project

**Comment by IIvanov8888** [comment]
thanks @v-bodnar , I got the latest version , but it seems like there is one more issue with jquery 
```javascript 
core.js:1440 ERROR ReferenceError: $ is not defined
    at SafeSubscriber.eval [as _next] (gallery.component.ts:98)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:239)
    at SafeSubscriber.next (Subscriber.js:186)
    at Subscriber._next (Subscriber.js:127)
    at Subscriber.next (Subscriber.js:91)
    at MapSubscriber._next (map.js:85)
    at MapSubscriber.Subscriber.next (Subscriber.js:91)
    at FilterSubscriber._next (filter.js:90)
    at FilterSubscriber.Subscriber.next (Subscriber.js:91)
    at MergeMapSubscriber.notifyNext (mergeMap.js:151)
```

Do you happen to see the thumbnails broken when displaying the images ? I need to zoom in and out to have them properly displayed.
<img width="1246" alt="screen shot 2018-01-24 at 22 13 28" src="https://user-images.githubusercontent.com/22252962/35357690-9b17043c-0154-11e8-80af-fc276425a42d.png">

**Comment by v-bodnar** [comment]
About jquery, try to run npm install jquery
As I have mentioned previously, I have added a lot of stuff in later commits (jquery, bootstrap, fontawesome, added some pipes), consider using version from 571099c49334180a69d723fa1374cce12d87bbd5

About problem with broken thumbnails, images are downloaded as you scroll down, there is a function that detects scrolling position and calculates if you have reached particular image. May be you are using gallery in a container with overflow: hidden, or there is some error calculating thumbnails size... Actually I  didn't face such behavior.

**Comment by IIvanov8888** [comment]
@v-bodnar thanks , I had mat-card as wrapper of the gallery , that seems to be an issue with the thumbnails.

**Comment by BenjaminBrandmeier** [comment]
I used a different approach via graphicsmagick to solve this. The fix will the issue for all images containing EXIF orientation information. Will be included in the next published version. Publishing the next version might take a while.
