### ISSUE TITLE
Angular 5

### ISSUE THREAD

**Issue by fpiergen** [BenjaminBrandmeier/angular2-image-gallery#68]
Having trouble with Angular 5. Is this a known issue?

**Comment by zoness32** [comment]
Angular 5 brings some breaking changes, the most notable of which is the removal of the HttpModule and its replacement with the HttpClientModule. I was able to fix most of the errors by replacing the references to Http with HttpClient and patching up a few other easy-to-fix things. I had to copy the source files directly into my project to fix the issues and keep them fixed, but once I'm finished with my project I'm hoping to get a PR out with the updates.

**Comment by efgonz** [comment]
There will be Angular 5 support?

**Comment by ngervasi** [comment]
Any news on Angular 5/6 support?

**Comment by BenjaminBrandmeier** [comment]
I paused this project for some time now and to be honest I suppose there won't be much improvements in the near future, but I'm planning on bumping this to be Angular 6 compatible and to add some performance improvements. I hope to publish an Angular 6 compatible version within June and will keep you up to date if its ready within this issue.

**Comment by BenjaminBrandmeier** [comment]
Angular 6 officially supported! Checkout out the latest version and let me know if there are any issues.
