### ISSUE TITLE
data.js not found when the option  [galleryName]="'yourGalleryName'" is added to the html 

### ISSUE THREAD

**Issue by sofiag** [BenjaminBrandmeier/angular2-image-gallery#73]
When trying to run the app with the suggested html code: 
```
<gallery
  [flexBorderSize]="3"
  [flexImageSize]="7"
  [galleryName]="'yourGalleryName'"
  [maxRowsPerPage]="100">
</gallery>
```

I get the error: 

```
GET http://localhost:4200/assets/img/gallery/yourGalleryName/data.json 404 (Not Found)

angular2-image-gallery.js:224 Did you run the convert script from angular2-image-gallery for your images first? Original error: [object Object]
```

I figured out by looking at your code that I have to remove the `[galleryName]="'yourGalleryName'"` option. 

I don't know how to set the `galleryName` for this to work, for the time being I just remove it.

**Comment by sofiag** [comment]
I hadn't seen that I have to run the convert command with the option --gName=yourGalleryName.
It is resolved

**Comment by BenjaminBrandmeier** [comment]
@sofiag The documentation states that all parameters are optional. 

[galleryName] and --gName is only needed if using multiple galleries.
