### ISSUE TITLE
Angular 7 Compatibility

### ISSUE THREAD

**Issue by Blamax** [BenjaminBrandmeier/angular2-image-gallery#74]
Hello!
Are there any plans to make the module usable for Angular 7?
Thanks in advance!

**Comment by NomiBZ** [comment]
I am joining...

**Comment by BenjaminBrandmeier** [comment]
definitely planned, most likely some day within the next 2 weeks

**Comment by BenjaminBrandmeier** [comment]
done, feedback would be highly appreciated!

**Comment by NomiBZ** [comment]
Thanks!
Why is the demo inactive?

**Comment by BenjaminBrandmeier** [comment]
@NomiBZ The demo is running fine for me at https://oidamo.de/angular2-image-gallery

Did I miss anything?
