### ISSUE TITLE
maxRowsPerPage does not jump to top on page switch

### ISSUE THREAD

**Issue by anetz89** [BenjaminBrandmeier/angular2-image-gallery#76]
First of all, great job! So far the best image gallery I found as npm package!

Using the maxRowsPerPage option adds two navigation buttons at the bottom of the gallery page. Whenever you click on one of those buttons, the page changes (as expected), but the vertical scroll position stays the same. This effect occurs, whenever the rows of the gallery extend the visible part of the browser window (using many images, for example of a wedding :) ).

Expected behavior would be a jump to the top of the gallery on page change.

**Comment by BenjaminBrandmeier** [comment]
Great suggestion Markus! Love your Advent of Code solutions btw!

The feature you have requested, seems to be resolved with the latest version of the gallery, so closing this issue for now.

Don't let the bed bugs bite!
