### ISSUE TITLE
How to integrate gallery in template?

### ISSUE THREAD

**Issue by leaffan** [BenjaminBrandmeier/angular2-image-gallery#77]
Pretty sure that's not an actual issue but my ignorance, but I just can't get the gallery images displayed on my page. I have run the conversion script successfully and all the image data is located correctly at *assets/img/gallery/* just as the script demanded. But after embedding the gallery directive in my template (as explained in point 5 of the step-by-step manual) I still get the following error in the console when loading my page:
Did you run the convert script from angular2-image-gallery for your images first? Original error: [object Object]
What could I have done wrong here?

**Comment by BenjaminBrandmeier** [comment]
Sorry for the (indeed very) late response on this issue. Have you figured out the issue? The convert script has been refactored with the latest release. If you are still interested, please give it a retry. If I don't here from you will close the issue within the next weeks.
