### ISSUE TITLE
error when running this:node node_modules/angular2-image-gallery/convert.js

### ISSUE THREAD

**Issue by DalalShimlani** [BenjaminBrandmeier/angular2-image-gallery#84]
when I try to run this 
node node_modules/angular2-image-gallery/convert.js /asstes/
i get this 

 asstes/
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module '/Users/lo/my-project/node_modules/angular2-image-gallery/convert.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by LeanderCoevoet** [comment]
You need to add the following as a devDependency: gm and onecolor.
So 
```
  "devDependencies": {
...
"gm": "^1.23.1",
"onecolor": "^3.1.0",
...
}
```

**Comment by BenjaminBrandmeier** [comment]
Actually I have to adjust the README. There are some additional ones to make the convert script running. But thanks for pointing out @LeanderCoevoet

**Comment by BenjaminBrandmeier** [comment]
All dependencies of the convert script are now part of the peerDependencies.
