### ISSUE TITLE
fix some litle boring issues

### ISSUE THREAD

**Issue by beubzz** [BenjaminBrandmeier/angular2-image-gallery#92]
Hello,
Thanks for you realy great and usefull package.
I'm using it on a project but i'm facing of two small but boring issues : 
this function have a bug : isScrolledIntoView() if the gallery is not in the viewport, some images dont' load. i have fixing this by return true all time in this function : isScrolledIntoView().
And on the end of this function : scaleGallery() i get a console error "EXCEPTION: Attempt to use a destroyed view: detectChanges" so i fixing this with : if (!this.changeDetectorRef['destroyed'])

Do you think it will be possible to have a fix for that and get a perfect new version ;) 

Regards

**Comment by BenjaminBrandmeier** [comment]
Appreciate you like the gallery. Please retry with the latest version, to see if your issues were resolved. Thanks!

**Comment by beubzz** [comment]
Seem to be good, Thanks a lot ;)

**Comment by BenjaminBrandmeier** [comment]
Glad to hear!
