### ISSUE TITLE
upgrade to angular 10 error

### ISSUE THREAD

**Issue by Fiehra** [BenjaminBrandmeier/angular2-image-gallery#97]
when upgrading my angular CLI from 9.1.2 to 10 the following error occurs.

![Capture](https://user-images.githubusercontent.com/45260245/99888004-47934280-2c49-11eb-9616-542628100487.JPG)

**Comment by Danubius1st** [comment]
Remove angular2-image-gallery
Upgrade angular
Install angular2-image-gallery

Hope this help.
